#!/bin/bash
echo "=== Oracle Forge — Team Server ==="
echo "Available tmux sessions:"
tmux ls 2>/dev/null || echo "  No sessions running. Start with: tmux new -s forge"
echo ""
echo "Quick commands:"
echo "  tmux attach -t forge      # Join the main session"
echo "  cd /shared/oracle-forge   # Project root"
echo "  cd /shared/DataAgentBench # DAB benchmark"
echo "  conda activate dab        # Activate DAB environment"
echo ""
echo "Server status:"
echo "  PostgreSQL: $(systemctl is-active postgresql)"
echo "  MongoDB:    $(systemctl is-active mongod)"
echo "  Toolbox:    $(curl -s http://localhost:5000/v1/tools > /dev/null 2>&1 && echo 'running' || echo 'not running')"
